schema_version = "1.0.0"

id = "johnnygizmo_modifier_node_edit_panel"
version = "0.2.2"
name = "JohnnyGizmo Special Values Node Edit Panel"
tagline = "Curves, Ramps, and Fonts, Bake Button from the Modifier Stack"
maintainer = "Johnny Matthews"
type = "add-on"

# website = ""
tags = ["Geometry Nodes"]

blender_version_min = "4.4.0"

license = [
  "SPDX:GPL-2.0-or-later",
]