schema_version = "1.0.0"

# Example of manifest file for a Blender extension
# Change the values according to your extension
id = "johnnygizmo_quick_cloth_tool"
version = "1.0.10"
name = "Quick Cloth Tool"
tagline = "Some Tools For Quick Cloth Simulation"
maintainer = "Johnny Matthews <johnny.matthews+blender@gmail.com>"
website = "https://github.com/johnnygizmo/extensions"
type = "add-on"
blender_version_min = "4.4.0"
license = [
  "SPDX:GPL-3.0-or-later",
]